title: Digital Twin SDK
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://digitaltwinsdk.com/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
